# Caso de uso de clusterização com KMeans
## A Batalha dos vizinhos em Toronto

Pacotes necessários para execução do caso de uso (instalação via linha de comando):
+ conda install -c conda-forge **geopy**
+ conda install -c anaconda **requests**
+ conda install -c conda-forge **folium**
+ conda install -c conda-forge **lxml**
+ conda install -c anaconda **html5lib**
+ conda install -c anaconda **beautifulsoup4**

<b>Objetivos - Parte 1</b>:

1) O dataframe de dados possui em três colunas: PostalCode, Borough e Neighbourhood


2) Processar apenas os exemplos que têm um bairro (Borough) atribuído. Ignorar os exemplos que não tem um bairro atribuído.

3) Pode existir mais de uma vizinhança no código postal de uma área. Por exemplo, na tabela da página da Wikipedia, você vai notar que M5A tem duas vizinhanças: Regent Park e Harbourfront. Essas duas linhas são combinadas em uma linha com os nomes separados por uma vírgula.

4) Se uma célula tiver um bairro (Borough), mas uma vizinhança (Neighborhood) não atribuída (Not assigned), a vizinhança terá o mesmo valor que o bairro.

In [15]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
df = pd.read_html('https://en.wikipedia.org/w/index.php?title=List_of_postal_codes_of_Canada:_M&oldid=977312452')[0]

df.columns = ['Postal Code','Borough','Neighborhood']
df

,Postal Code,Borough,Neighborhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

In [16]:
df = df[df.Borough != 'Not assigned']
df

,Postal Code,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [17]:
df.loc[df['Neighborhood'] =='Not assigned' , 'Neighborhood'] = df['Borough']
df

,Postal Code,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [18]:
# Resetar os índices
df.groupby(['Postal Code','Borough'])['Neighborhood'].apply(lambda x: ','.join(x.astype(str))).reset_index()

,Postal Code,Borough,Neighborhood
0,M1B,Scarborough,"Malvern, Rouge"
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
2,M1E,Scarborough,"Guildwood, Morningside, West Hill"
3,M1G,Scarborough,Woburn
4,M1H,Scarborough,Cedarbrae
...,...,...,...
98,M9N,York,Weston
99,M9P,Etobicoke,Westmount
100,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ..."
101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
102,M9W,Etobicoke,"Northwest, West Humber - Clairville"

In [19]:
df.shape

(103, 3)

<b>Objetivos - Parte 2</b>:

1) Agora que temos um dataframe do código postal de cada vizinhança, junto com o nome do bairro, podemos utilizar os dados de localização do Foursquare.

2) Explorar e clusterizar os bairros de Toronto.

<b> Importar as latitudes e longitudes, de acordo com o código postal </b>

In [23]:
df1 = pd.read_csv("https://cocl.us/Geospatial_data")
df1

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [24]:
df = pd.merge(df, df1, on = "Postal Code")
df

,Postal Code,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
...,...,...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.653654,-79.506944
99,M4Y,Downtown Toronto,Church and Wellesley,43.665860,-79.383160
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C...",43.662744,-79.321558
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",43.636258,-79.498509
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",43.628841,-79.520999

<b>Objetivos - Parte 3</b>:

Gerar mapa para visualizar os bairros e como eles se agrupam.

<b> Importar os pacotes necessários para visualizar e analisar o mapa </b>

In [25]:

from geopy.geocoders import Nominatim 

import requests 
from pandas.io.json import json_normalize 

import matplotlib.cm as cm
import matplotlib.colors as colors

from sklearn.cluster import KMeans

import folium 

print('Pacotes importados.')

Pacotes importados.

In [26]:
#Obter as coordenadas geográficas de Toronto, no Canadá.

address = 'Toronto, ON, Canada'

geolocator = Nominatim(user_agent="to_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('As coordenadas geográficas de Toronto, Canadá são {}, {}.'.format(latitude, longitude))

As coordenadas geográficas de Toronto, Canadá são 43.6534817, -79.3839347.

In [28]:
# Criar um mapa de Toronto usando os valores de latitude e longitude.
map_Toronto = folium.Map(location=[latitude,longitude], zoom_start=10)

# Adicionar marcadores ao mapa
for lat, lng, borough, neighborhood in zip(df['Latitude'], df['Longitude'], df['Borough'], df['Neighborhood']):
    label = '{}, {}'.format(neighborhood,borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_Toronto)  
    
map_Toronto

![map1.JPG](https://raw.githubusercontent.com/sarthak815/Coursera_Capstone/master/map1.JPG)

<b>Definir as credenciais de acesso ao Foursquare:</b>

Crie as suas próprias credenciais no link: https://developer.foursquare.com

In [29]:
# Credenciais do Foursquare
CLIENT_ID = 'EILREA14SNMZ0CWXNM0ND3WL5RIVV1B41U1NYADE24SPTYOX'
CLIENT_SECRET = 'FNAPNA3MSBWLU2YZ15RH4VQPI0OS5MAFS0ARQTDK1VDZM4JR'
VERSION = '20180604'

In [30]:
# definir raio e limite de locais para buscar
radius=500
LIMIT=100

In [31]:

def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # criar a URL para acessar a API
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # fazer a requisição GET
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # retornar apenas as informações relevantes para cada local próximo
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighbourhood', 
                  'Neighbourhood Latitude', 
                  'Neighbourhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [32]:

toronto_venues = getNearbyVenues(names=df['Neighborhood'],
                                   latitudes=df['Latitude'],
                                   longitudes=df['Longitude']
                                  )

Parkwoods
Victoria Village
Regent Park, Harbourfront
Lawrence Manor, Lawrence Heights
Queen's Park, Ontario Provincial Government
Islington Avenue, Humber Valley Village
Malvern, Rouge
Don Mills
Parkview Hill, Woodbine Gardens
Garden District, Ryerson
Glencairn
West Deane Park, Princess Gardens, Martin Grove, Islington, Cloverdale
Rouge Hill, Port Union, Highland Creek
Don Mills
Woodbine Heights
St. James Town
Humewood-Cedarvale
Eringate, Bloordale Gardens, Old Burnhamthorpe, Markland Wood
Guildwood, Morningside, West Hill
The Beaches
Berczy Park
Caledonia-Fairbanks
Woburn
Leaside
Central Bay Street
Christie
Cedarbrae
Hillcrest Village
Bathurst Manor, Wilson Heights, Downsview North
Thorncliffe Park
Richmond, Adelaide, King
Dufferin, Dovercourt Village
Scarborough Village
Fairview, Henry Farm, Oriole
Northwood Park, York University
East Toronto, Broadview North (Old East York)
Harbourfront East, Union Station, Toronto Islands
Little Portugal, Trinity
Kennedy Park, Ionview, East Birchmount Park
Bayview Village
Downsview
The Danforth West, Riverdale
Toronto Dominion Centre, Design Exchange
Brockton, Parkdale Village, Exhibition Place
Golden Mile, Clairlea, Oakridge
York Mills, Silver Hills
Downsview
India Bazaar, The Beaches West
Commerce Court, Victoria Hotel
North Park, Maple Leaf Park, Upwood Park
Humber Summit
Cliffside, Cliffcrest, Scarborough Village West
Willowdale, Newtonbrook
Downsview
Studio District
Bedford Park, Lawrence Manor East
Del Ray, Mount Dennis, Keelsdale and Silverthorn
Humberlea, Emery
Birch Cliff, Cliffside West
Willowdale, Willowdale East
Downsview
Lawrence Park
Roselawn
Runnymede, The Junction North
Weston
Dorset Park, Wexford Heights, Scarborough Town Centre
York Mills West
Davisville North
Forest Hill North & West, Forest Hill Road Park
High Park, The Junction South
Westmount
Wexford, Maryvale
Willowdale, Willowdale West
North Toronto West, Lawrence Park
The Annex, North Midtown, Yorkville
Parkdale, Roncesvalles
Canada Post Gateway Processing Centre
Kingsview Village, St. Phillips, Martin Grove Gardens, Richview Gardens
Agincourt
Davisville
University of Toronto, Harbord
Runnymede, Swansea
Clarks Corners, Tam O'Shanter, Sullivan
Moore Park, Summerhill East
Kensington Market, Chinatown, Grange Park
Milliken, Agincourt North, Steeles East, L'Amoreaux East
Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park
CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport
New Toronto, Mimico South, Humber Bay Shores
South Steeles, Silverstone, Humbergate, Jamestown, Mount Olive, Beaumond Heights, Thistletown, Albion Gardens
Steeles West, L'Amoreaux West
Rosedale
Stn A PO Boxes
Alderwood, Long Branch
Northwest, West Humber - Clairville
Upper Rouge
St. James Town, Cabbagetown
First Canadian Place, Underground city
The Kingsway, Montgomery Road, Old Mill North
Church and Wellesley
Business reply mail Processing Centre, South Central Letter Processing Plant Toronto
Old Mill South, King's Mill Park, Sunnylea, Humber Bay, Mimico NE, The Queensway East, Royal York South East, Kingsway Park South East
Mimico NW, The Queensway West, South of Bloor, Kingsway Park South West, Royal York South West

<b>Checando o tamanho do dataframe:</b>

In [33]:
print(toronto_venues.shape)
toronto_venues.head()

(2313, 7)

,Neighbourhood,Neighbourhood Latitude,Neighbourhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Parkwoods,43.753259,-79.329656,Brookbanks Park,43.754751,-79.328439,Park
1,Parkwoods,43.753259,-79.329656,Variety Store,43.752018,-79.332833,Food and Beverage Retail
2,Victoria Village,43.725882,-79.315572,Victoria Village Arena,43.723321,-79.315512,Hockey Stadium
3,Victoria Village,43.725882,-79.315572,Tim Hortons,43.725517,-79.313103,Coffee Shop
4,Victoria Village,43.725882,-79.315572,Portugril,43.725482,-79.312809,Portuguese Restaurant

<b>O número de locais por vizinhança:</b>

In [34]:
toronto_venues.groupby('Neighbourhood').count()

,Neighbourhood Latitude,Neighbourhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Neighbourhood,,,,,,
Agincourt,2,2,2,2,2,2
"Alderwood, Long Branch",7,7,7,7,7,7
"Bathurst Manor, Wilson Heights, Downsview North",17,17,17,17,17,17
Bayview Village,3,3,3,3,3,3
"Bedford Park, Lawrence Manor East",20,20,20,20,20,20
...,...,...,...,...,...,...
"Willowdale, Willowdale East",35,35,35,35,35,35
"Willowdale, Willowdale West",5,5,5,5,5,5
Woburn,3,3,3,3,3,3
Woodbine Heights,5,5,5,5,5,5
York Mills West,4,4,4,4,4,4

<b>Vamos ver quantas categorias exclusivas podem ser selecionadas de todos os locais</b>

In [35]:
print('Existem {} categorias únicas.'.format(len(toronto_venues['Venue Category'].unique())))

Existem 273 categorias únicas.

<b> Analisando cada vizinhança</b>

In [36]:
# codificação one hot
toronto_onehot = pd.get_dummies(toronto_venues[['Venue Category']], prefix="", prefix_sep="")

# adicionar a coluna vizinhança novamente ao dataframe
toronto_onehot['Neighborhood'] = toronto_venues['Neighbourhood'] 

fixed_columns = [toronto_onehot.columns[-1]] + list(toronto_onehot.columns[:-1])
toronto_onehot = toronto_onehot[fixed_columns]

toronto_onehot.head()

,Women's Store,Adult Store,Afghan Restaurant,Airport,Airport Food Court,Airport Gate,Airport Lounge,Airport Service,Airport Terminal,American Restaurant,...,Travel and Transportation,Vegan and Vegetarian Restaurant,Video Games Store,Vietnamese Restaurant,Vintage and Thrift Store,Warehouse or Wholesale Store,Whisky Bar,Wine Bar,Wine Store,Wings Joint
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:

toronto_onehot.shape

(2313, 273)

<b>A seguir, vamos agrupar as linhas por vizinhança e calcular a média da frequência de cada categoria</b>

In [38]:
toronto_grouped = toronto_onehot.groupby('Neighborhood').mean().reset_index()
toronto_grouped

,Neighborhood,Women's Store,Adult Store,Afghan Restaurant,Airport,Airport Food Court,Airport Gate,Airport Lounge,Airport Service,Airport Terminal,...,Travel and Transportation,Vegan and Vegetarian Restaurant,Video Games Store,Vietnamese Restaurant,Vintage and Thrift Store,Warehouse or Wholesale Store,Whisky Bar,Wine Bar,Wine Store,Wings Joint
0,Agincourt,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,"Alderwood, Long Branch",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,"Bathurst Manor, Wilson Heights, Downsview North",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,Bayview Village,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,"Bedford Park, Lawrence Manor East",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.05,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,"Willowdale, Willowdale East",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.057143,0.0,0.0,0.0,0.0,0.0,0.0
92,"Willowdale, Willowdale West",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
93,Woburn,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
94,Woodbine Heights,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
95,York Mills West,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0


<b>Vamos imprimir cada vizinhança junto com os 5 locais mais comuns</b>

In [39]:
num_top_venues = 5

for hood in toronto_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = toronto_grouped[toronto_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Agincourt----
                 venue  freq
0       Clothing Store   0.5
1       Breakfast Spot   0.5
2        Women's Store   0.0
3                Motel   0.0
4  Moroccan Restaurant   0.0


----Alderwood, Long Branch----
           venue  freq
0       Pizzeria  0.29
1    Coffee Shop  0.14
2  Sandwich Spot  0.14
3     Playground  0.14
4   Burger Joint  0.14


----Bathurst Manor, Wilson Heights, Downsview North----
                       venue  freq
0                Coffee Shop  0.12
1                       Deli  0.06
2              Shopping Mall  0.06
3  Middle Eastern Restaurant  0.06
4              Sandwich Spot  0.06


----Bayview Village----
                venue  freq
0  Chinese Restaurant  0.33
1                Café  0.33
2      Shopping Plaza  0.33
3       Women's Store  0.00
4  Mobile Phone Store  0.00


----Bedford Park, Lawrence Manor East----
                venue  freq
0        Fuel Station  0.10
1     Thai Restaurant  0.10
2  Persian Restaurant  0.05
3    Greek Restaurant  0.05
4             Butcher  0.05


----Berczy Park----
          venue  freq
0   Coffee Shop  0.12
1        Bakery  0.04
2           Pub  0.04
3           Bar  0.03
4  Cocktail Bar  0.03


----Birch Cliff, Cliffside West----
                    venue  freq
0                Pizzeria  0.25
1  Arts and Entertainment  0.25
2                    Café  0.25
3                     Pub  0.25
4                  Museum  0.00


----Brockton, Parkdale Village, Exhibition Place----
                venue  freq
0                Café  0.12
1              Bakery  0.08
2         Coffee Shop  0.08
3      Breakfast Spot  0.04
4  Italian Restaurant  0.04


----Business reply mail Processing Centre, South Central Letter Processing Plant Toronto----
                  venue  freq
0  Fast Food Restaurant  0.13
1                Garden  0.07
2            Smoke Shop  0.07
3              Boutique  0.07
4        Farmers Market  0.07


----CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport----
              venue  freq
0    Airport Lounge  0.14
1   Airport Service  0.14
2  Airport Terminal  0.10
3               Bar  0.05
4       Coffee Shop  0.05


----Caledonia-Fairbanks----
                       venue  freq
0                     Bakery  0.33
1              Fishing Store  0.33
2                       Park  0.33
3              Women's Store  0.00
4  Middle Eastern Restaurant  0.00


----Canada Post Gateway Processing Centre----
                venue  freq
0         Coffee Shop  0.20
1               Hotel  0.13
2        Fuel Station  0.13
3       Sandwich Spot  0.07
4  Mexican Restaurant  0.07


----Cedarbrae----
                   venue  freq
0  Sports and Recreation  0.14
1                 Bakery  0.14
2        Thai Restaurant  0.14
3           Fuel Station  0.14
4    Fried Chicken Joint  0.14


----Central Bay Street----
                  venue  freq
0           Coffee Shop  0.15
1                  Café  0.07
2  Fast Food Restaurant  0.05
3   Japanese Restaurant  0.05
4            Restaurant  0.03


----Christie----
           venue  freq
0           Café  0.27
1           Park  0.18
2  Grocery Store  0.18
3    Candy Store  0.09
4     Restaurant  0.09


----Church and Wellesley----
                 venue  freq
0          Coffee Shop  0.08
1     Sushi Restaurant  0.06
2  Japanese Restaurant  0.05
3              Gay Bar  0.04
4                 Café  0.03


----Clarks Corners, Tam O'Shanter, Sullivan----
                venue  freq
0        Fuel Station  0.31
1            Pizzeria  0.15
2        Intersection  0.08
3         Coffee Shop  0.08
4  Chinese Restaurant  0.08


----Cliffside, Cliffcrest, Scarborough Village West----
                       venue  freq
0           Harbor or Marina   0.5
1                      Motel   0.5
2              Women's Store   0.0
3  Middle Eastern Restaurant   0.0
4        Moroccan Restaurant   0.0


----Commerce Court, Victoria Hotel----
         venue  freq
0  Coffee Shop  0.12
1         Café  0.07
2        Hotel  0.07
3   Restaurant  0.07
4         Deli  0.04


----Davisville----
                venue  freq
0            Pizzeria  0.08
1       Sandwich Spot  0.08
2        Dessert Shop  0.08
3  Italian Restaurant  0.06
4                Café  0.06


----Davisville North----
               venue  freq
0     Breakfast Spot  0.12
1      Sandwich Spot  0.12
2  Convenience Store  0.12
3               Park  0.12
4              Hotel  0.12


----Del Ray, Mount Dennis, Keelsdale and Silverthorn----
                  venue  freq
0  Fast Food Restaurant   0.2
1          Fuel Station   0.2
2         Sandwich Spot   0.2
3                   Bar   0.2
4    Mexican Restaurant   0.2


----Don Mills----
                  venue  freq
0   Japanese Restaurant  0.10
1         Grocery Store  0.05
2         Travel Agency  0.05
3  Caribbean Restaurant  0.05
4   Fried Chicken Joint  0.05


----Dorset Park, Wexford Heights, Scarborough Town Centre----
                       venue  freq
0          Indian Restaurant  0.50
1         Pet Supplies Store  0.25
2      Vietnamese Restaurant  0.25
3  Middle Eastern Restaurant  0.00
4        Moroccan Restaurant  0.00


----Downsview----
          venue  freq
0  Fuel Station  0.17
1          Park  0.17
2   Coffee Shop  0.08
3    Food Court  0.08
4       Exhibit  0.08


----Dufferin, Dovercourt Village----
           venue  freq
0       Pharmacy  0.14
1         Bakery  0.14
2  Grocery Store  0.07
3    Music Venue  0.07
4   Intersection  0.07


----East Toronto, Broadview North (Old East York)----
                 venue  freq
0                 Park  0.50
1    Convenience Store  0.25
2  Rental Car Location  0.25
3  Miscellaneous Store  0.00
4                Motel  0.00


----Eringate, Bloordale Gardens, Old Burnhamthorpe, Markland Wood----
          venue  freq
0      Pharmacy  0.09
1          Park  0.09
2  Fuel Station  0.09
3          Café  0.09
4    Beer Store  0.09


----Fairview, Henry Farm, Oriole----
                  venue  freq
0        Clothing Store  0.14
1           Coffee Shop  0.06
2  Fast Food Restaurant  0.05
3         Women's Store  0.03
4            Shoe Store  0.03


----First Canadian Place, Underground city----
         venue  freq
0  Coffee Shop  0.10
1         Café  0.08
2   Restaurant  0.06
3        Hotel  0.06
4         Deli  0.04


----Forest Hill North & West, Forest Hill Road Park----
                 venue  freq
0         Fuel Station  0.50
1         Hiking Trail  0.25
2   Mexican Restaurant  0.25
3  Miscellaneous Store  0.00
4                Motel  0.00


----Garden District, Ryerson----
             venue  freq
0      Coffee Shop  0.09
1   Clothing Store  0.07
2             Café  0.04
3  Bubble Tea Shop  0.04
4  Cosmetics Store  0.03


----Glencairn----
                 venue  freq
0    Convenience Store   0.2
1  Japanese Restaurant   0.2
2     Sushi Restaurant   0.2
3               Bakery   0.2
4   Italian Restaurant   0.2


----Golden Mile, Clairlea, Oakridge----
           venue  freq
0       Bus Line  0.22
1         Bakery  0.22
2   Soccer Field  0.11
3   Intersection  0.11
4  Metro Station  0.11


----Guildwood, Morningside, West Hill----
                 venue  freq
0           Donut Shop   0.2
1       Breakfast Spot   0.2
2  Rental Car Location   0.2
3   Mexican Restaurant   0.2
4    Electronics Store   0.2


----Harbourfront East, Union Station, Toronto Islands----
         venue  freq
0  Coffee Shop  0.12
1         Café  0.05
2     Aquarium  0.05
3        Hotel  0.04
4   Restaurant  0.03


----High Park, The Junction South----
                   venue  freq
0  Arts and Crafts Store  0.08
1     Mexican Restaurant  0.08
2                    Bar  0.08
3                 Bakery  0.08
4        Thai Restaurant  0.08


----Hillcrest Village----
                      venue  freq
0                  Dog Park   0.5
1  Mediterranean Restaurant   0.5
2       Miscellaneous Store   0.0
3             Movie Theater   0.0
4                     Motel   0.0


----Humber Summit----
                       venue  freq
0             Clothing Store   1.0
1  Middle Eastern Restaurant   0.0
2                      Motel   0.0
3        Moroccan Restaurant   0.0
4                   Monument   0.0


----Humberlea, Emery----
                       venue  freq
0   Furniture and Home Store   0.5
1              Grocery Store   0.5
2  Middle Eastern Restaurant   0.0
3                      Motel   0.0
4        Moroccan Restaurant   0.0


----Humewood-Cedarvale----
            venue  freq
0    Hiking Trail  0.25
1  Hockey Stadium  0.25
2      Playground  0.25
3           Field  0.25
4  History Museum  0.00


----India Bazaar, The Beaches West----
                      venue  freq
0                      Park  0.10
1      Fast Food Restaurant  0.10
2                Playground  0.05
3  Food and Beverage Retail  0.05
4                  Pizzeria  0.05


----Kennedy Park, Ionview, East Birchmount Park----
                venue  freq
0      Discount Store  0.25
1         Coffee Shop  0.12
2   Convenience Store  0.12
3    Department Store  0.12
4  Chinese Restaurant  0.12


----Kensington Market, Chinatown, Grange Park----
                   venue  freq
0                   Café  0.06
1  Vietnamese Restaurant  0.05
2    Dumpling Restaurant  0.04
3                    Bar  0.04
4                 Bakery  0.04


----Kingsview Village, St. Phillips, Martin Grove Gardens, Richview Gardens----
                venue  freq
0            Bus Line  0.33
1       Sandwich Spot  0.33
2  Mobile Phone Store  0.33
3       Women's Store  0.00
4               Motel  0.00


----Lawrence Manor, Lawrence Heights----
                       venue  freq
0   Furniture and Home Store  0.25
1             Clothing Store  0.17
2  Fashion Accessories Store  0.08
3                Event Space  0.08
4      Vietnamese Restaurant  0.08


----Lawrence Park----
                       venue  freq
0                       Park  0.33
1                   Bus Line  0.33
2            Organic Grocery  0.33
3              Women's Store  0.00
4  Middle Eastern Restaurant  0.00


----Leaside----
                   venue  freq
0            Coffee Shop  0.10
1  Sporting Goods Retail  0.07
2           Burger Joint  0.07
3             Sports Bar  0.03
4    Fish and Chips Shop  0.03


----Little Portugal, Trinity----
         venue  freq
0          Bar  0.12
1  Men's Store  0.06
2  Coffee Shop  0.05
3       Bakery  0.05
4     Boutique  0.05


----Malvern, Rouge----
                       venue  freq
0       Fast Food Restaurant   0.5
1               Fuel Station   0.5
2  Middle Eastern Restaurant   0.0
3        Moroccan Restaurant   0.0
4                   Monument   0.0


----Milliken, Agincourt North, Steeles East, L'Amoreaux East----
                       venue  freq
0               Intersection  0.33
1                 Playground  0.33
2                       Park  0.33
3  Middle Eastern Restaurant  0.00
4                      Motel  0.00


----Mimico NW, The Queensway West, South of Bloor, Kingsway Park South West, Royal York South West----
               venue  freq
0        Wings Joint  0.08
1  Convenience Store  0.08
2             Bakery  0.08
3           Beer Bar  0.08
4      Sandwich Spot  0.08


----Moore Park, Summerhill East----
                   venue  freq
0      Convenience Store  0.33
1           Intersection  0.33
2        Cosmetics Store  0.33
3     Persian Restaurant  0.00
4  Performing Arts Venue  0.00


----New Toronto, Mimico South, Humber Bay Shores----
                  venue  freq
0     Health Food Store  0.11
1                Bakery  0.11
2          Fuel Station  0.11
3          Liquor Store  0.11
4  Fast Food Restaurant  0.11


----North Park, Maple Leaf Park, Upwood Park----
                 venue  freq
0               Bakery   1.0
1        Women's Store   0.0
2  Miscellaneous Store   0.0
3                Motel   0.0
4  Moroccan Restaurant   0.0


----North Toronto West, Lawrence Park----
                venue  freq
0      Clothing Store  0.15
1         Coffee Shop  0.15
2          Bagel Shop  0.08
3          Hair Salon  0.08
4  Chinese Restaurant  0.08


----Northwest, West Humber - Clairville----
                 venue  freq
0          Print Store   0.2
1                  Bar   0.2
2        Garden Center   0.2
3  Rental Car Location   0.2
4            Drugstore   0.2


----Northwood Park, York University----
                  venue  freq
0  Caribbean Restaurant   0.2
1         Sandwich Spot   0.2
2          Fuel Station   0.2
3                   Bar   0.2
4           Coffee Shop   0.2


----Old Mill South, King's Mill Park, Sunnylea, Humber Bay, Mimico NE, The Queensway East, Royal York South East, Kingsway Park South East----
                       venue  freq
0          Convenience Store  0.33
1  Travel and Transportation  0.33
2                       Park  0.33
3                      Motel  0.00
4        Moroccan Restaurant  0.00


----Parkdale, Roncesvalles----
            venue  freq
0  Breakfast Spot   0.2
1    Dessert Shop   0.1
2   Movie Theater   0.1
3             Bar   0.1
4        Dog Park   0.1


----Parkview Hill, Woodbine Gardens----
            venue  freq
0        Pizzeria  0.33
1     Coffee Shop  0.17
2  Breakfast Spot  0.17
3       Gastropub  0.17
4        Pharmacy  0.17


----Parkwoods----
                       venue  freq
0                       Park   0.5
1   Food and Beverage Retail   0.5
2              Women's Store   0.0
3  Middle Eastern Restaurant   0.0
4        Moroccan Restaurant   0.0


----Queen's Park, Ontario Provincial Government----
                 venue  freq
0          Coffee Shop  0.19
1     Sushi Restaurant  0.06
2         Burger Joint  0.04
3                 Café  0.04
4  Fried Chicken Joint  0.04


----Regent Park, Harbourfront----
                   venue  freq
0            Coffee Shop  0.12
1                    Pub  0.05
2  Performing Arts Venue  0.05
3                   Park  0.05
4                 Bakery  0.05


----Richmond, Adelaide, King----
             venue  freq
0             Café  0.08
1            Hotel  0.07
2      Coffee Shop  0.06
3   Clothing Store  0.03
4  Thai Restaurant  0.03


----Rosedale----
                       venue  freq
0                       Park  0.50
1               Hiking Trail  0.25
2                 Playground  0.25
3              Women's Store  0.00
4  Middle Eastern Restaurant  0.00


----Roselawn----
                    venue  freq
0                  Garden   0.5
1  Arts and Entertainment   0.5
2           Women's Store   0.0
3           Movie Theater   0.0
4                   Motel   0.0


----Rouge Hill, Port Union, Highland Creek----
                 venue  freq
0                  Bar   1.0
1        Women's Store   0.0
2  Miscellaneous Store   0.0
3                Motel   0.0
4  Moroccan Restaurant   0.0


----Runnymede, Swansea----
                venue  freq
0         Coffee Shop  0.08
1                 Pub  0.08
2            Pizzeria  0.08
3                Café  0.08
4  Italian Restaurant  0.06


----Runnymede, The Junction North----
                      venue  freq
0                      Park  0.50
1         Convenience Store  0.25
2  Furniture and Home Store  0.25
3                    Market  0.00
4  Mediterranean Restaurant  0.00


----Scarborough Village----
                      venue  freq
0                  Pizzeria  0.33
1                Playground  0.33
2            Cannabis Store  0.33
3                    Market  0.00
4  Mediterranean Restaurant  0.00


----South Steeles, Silverstone, Humbergate, Jamestown, Mount Olive, Beaumond Heights, Thistletown, Albion Gardens----
                  venue  freq
0              Pizzeria  0.18
1         Grocery Store  0.18
2              Pharmacy  0.09
3        Hockey Stadium  0.09
4  Fast Food Restaurant  0.09


----St. James Town----
            venue  freq
0           Hotel  0.05
1     Coffee Shop  0.05
2  Clothing Store  0.05
3      Restaurant  0.04
4            Café  0.03


----St. James Town, Cabbagetown----

              venue  freq
0       Coffee Shop  0.07
1              Café  0.07
2              Park  0.04
3  Ice Cream Parlor  0.04
4          Pizzeria  0.04


----Steeles West, L'Amoreaux West----
                  venue  freq
0  Fast Food Restaurant  0.13
1              Pharmacy  0.07
2           Coffee Shop  0.07
3       Bubble Tea Shop  0.07
4          Burger Joint  0.07


----Stn A PO Boxes----
                venue  freq
0         Coffee Shop  0.10
1                 Pub  0.04
2              Bakery  0.04
3               Hotel  0.03
4  Seafood Restaurant  0.03


----Studio District----
                venue  freq
0         Coffee Shop  0.08
1                Café  0.08
2  Seafood Restaurant  0.05
3              Bakery  0.05
4         Music Store  0.05


----Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park----
                 venue  freq
0           Bagel Shop  0.15
1                  Pub  0.15
2         Liquor Store  0.08
3  American Restaurant  0.08
4           Restaurant  0.08


----The Annex, North Midtown, Yorkville----
            venue  freq
0   Sandwich Spot  0.16
1            Café  0.16
2     Coffee Shop  0.11
3  History Museum  0.05
4    Liquor Store  0.05


----The Beaches----
               venue  freq
0  Health Food Store  0.25
1        Coffee Shop  0.25
2       Hiking Trail  0.25
3           Wine Bar  0.00
4      Movie Theater  0.00


----The Danforth West, Riverdale----
                venue  freq
0    Greek Restaurant  0.20
1    Sushi Restaurant  0.06
2  Italian Restaurant  0.05
3         Coffee Shop  0.05
4           Bookstore  0.03


----The Kingsway, Montgomery Road, Old Mill North----
                       venue  freq
0                      River   1.0
1  Middle Eastern Restaurant   0.0
2                      Motel   0.0
3        Moroccan Restaurant   0.0
4                   Monument   0.0


----Thorncliffe Park----
                  venue  freq
0          Fuel Station  0.11
1     Indian Restaurant  0.11
2        Discount Store  0.06
3           Supermarket  0.06
4  Fast Food Restaurant  0.06


----Toronto Dominion Centre, Design Exchange----
         venue  freq
0        Hotel  0.10
1  Coffee Shop  0.09
2         Café  0.07
3   Restaurant  0.05
4   Steakhouse  0.03


----University of Toronto, Harbord----
           venue  freq
0           Café  0.18
1  Sandwich Spot  0.08
2      Bookstore  0.08
3         Bakery  0.05
4            Pub  0.05


----Victoria Village----
                      venue  freq
0     Portuguese Restaurant  0.25
1            Hockey Stadium  0.25
2               Coffee Shop  0.25
3              Fuel Station  0.25
4  Mediterranean Restaurant  0.00


----West Deane Park, Princess Gardens, Martin Grove, Islington, Cloverdale----
                 venue  freq
0             Tea Room  0.33
1  Fish and Chips Shop  0.33
2   Chinese Restaurant  0.33
3  Miscellaneous Store  0.00
4                Motel  0.00


----Westmount----
                       venue  freq
0                   Pizzeria   0.5
1                Coffee Shop   0.5
2  Middle Eastern Restaurant   0.0
3                      Motel   0.0
4        Moroccan Restaurant   0.0


----Weston----
                       venue  freq
0             Farmers Market  0.33
1                        Spa  0.33
2   Mediterranean Restaurant  0.33
3              Women's Store  0.00
4  Middle Eastern Restaurant  0.00


----Wexford, Maryvale----
                       venue  freq
0                   Pharmacy  0.25
1              Sandwich Spot  0.25
2                     Bakery  0.25
3  Middle Eastern Restaurant  0.25
4   Mediterranean Restaurant  0.00


----Willowdale, Newtonbrook----
                 venue  freq
0                 Park   1.0
1        Women's Store   0.0
2   Mexican Restaurant   0.0
3  Moroccan Restaurant   0.0
4             Monument   0.0


----Willowdale, Willowdale East----
                   venue  freq
0       Ramen Restaurant  0.09
1          Shopping Mall  0.06
2  Vietnamese Restaurant  0.06
3                   Café  0.06
4          Movie Theater  0.03


----Willowdale, Willowdale West----
            venue  freq
0        Pizzeria   0.2
1     Coffee Shop   0.2
2    Fuel Station   0.2
3  Discount Store   0.2
4        Pharmacy   0.2


----Woburn----
                   venue  freq
0                   Park  0.33
1            Coffee Shop  0.33
2  Korean BBQ Restaurant  0.33
3          Women's Store  0.00
4    Miscellaneous Store  0.00


----Woodbine Heights----
        venue  freq
0    Pharmacy   0.2
1        Park   0.2
2        Café   0.2
3    Bus Stop   0.2
4  Beer Store   0.2


----York Mills West----
                 venue  freq
0                 Park  0.50
1    Convenience Store  0.25
2        Jewelry Store  0.25
3  Miscellaneous Store  0.00
4                Motel  0.00

<b>Vamos colocar essa informação em um dataframe</b>

In [40]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [41]:
import numpy as np

num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = toronto_grouped['Neighborhood']

for ind in np.arange(toronto_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(toronto_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Agincourt,Clothing Store,Breakfast Spot,Escape Room,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Electronics Store,Empanada Restaurant,Wings Joint
1,"Alderwood, Long Branch",Pizzeria,Burger Joint,Coffee Shop,Pub,Playground,Sandwich Spot,Eastern European Restaurant,Doner Restaurant,Donut Shop,Drugstore
2,"Bathurst Manor, Wilson Heights, Downsview North",Coffee Shop,Chinese Restaurant,Shopping Mall,Bridal Store,Sandwich Spot,Supermarket,Restaurant,Sushi Restaurant,Middle Eastern Restaurant,Ice Cream Parlor
3,Bayview Village,Café,Shopping Plaza,Chinese Restaurant,Electronics Store,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Wings Joint
4,"Bedford Park, Lawrence Manor East",Thai Restaurant,Fuel Station,Coffee Shop,Indian Restaurant,Italian Restaurant,Liquor Store,Comfort Food Restaurant,Grocery Store,Persian Restaurant,Pharmacy

<b> Realizar a clusterização da vizinhança</b>

In [42]:
# Número de clusters
kclusters = 5


toronto_grouped_clustering = toronto_grouped.drop('Neighborhood', 1)

kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(toronto_grouped_clustering)

# checar os rótulos do cluster gerado para cada linha do dataframe
#kmeans.labels_[0:10] 
kmeans.labels_

array([3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1])

In [43]:
# Adicionar os rótulos do cluster
neighborhoods_venues_sorted.insert(0, 'Cluster_Labels', kmeans.labels_)

toronto_merged = df

# Juntar o datagrame toronto_grouped com toronto_data para adicionar as informações de 
# latitude e longitude para cada vizinhança
toronto_merged = toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

toronto_merged.head()

,Postal Code,Borough,Neighborhood,Latitude,Longitude,Cluster_Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,M3A,North York,Parkwoods,43.753259,-79.329656,1.0,Park,Food and Beverage Retail,Wings Joint,Electronics Store,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Empanada Restaurant
1,M4A,North York,Victoria Village,43.725882,-79.315572,0.0,Fuel Station,Coffee Shop,Hockey Stadium,Portuguese Restaurant,Electronics Store,Doner Restaurant,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636,0.0,Coffee Shop,Pub,Italian Restaurant,Park,Performing Arts Venue,Bakery,Art Gallery,Thai Restaurant,Theater,Beer Store
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763,0.0,Furniture and Home Store,Clothing Store,Fashion Accessories Store,Party Supply Store,Boutique,Event Space,Vietnamese Restaurant,Coffee Shop,Flea Market,Education
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494,0.0,Coffee Shop,Sushi Restaurant,Fried Chicken Joint,Burger Joint,Café,Wings Joint,Seafood Restaurant,Sandwich Spot,Bubble Tea Shop,Restaurant

In [44]:
toronto_merged=toronto_merged.dropna()

In [45]:

toronto_merged['Cluster_Labels'] = toronto_merged.Cluster_Labels.astype(int)

**Visualizar os clusters**

In [46]:
# Criar o mapa
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# Alterar as cores dos clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# Adicionar os marcadores no mapa
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Neighborhood'], toronto_merged['Cluster_Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

![map2.JPG](https://raw.githubusercontent.com/sarthak815/Coursera_Capstone/master/map2.JPG)


<b>Examinar os Clusters</b>

Cluster 0

In [47]:
toronto_merged.loc[toronto_merged['Cluster_Labels'] == 0, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Borough,Cluster_Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
1,North York,0,Fuel Station,Coffee Shop,Hockey Stadium,Portuguese Restaurant,Electronics Store,Doner Restaurant,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant
2,Downtown Toronto,0,Coffee Shop,Pub,Italian Restaurant,Park,Performing Arts Venue,Bakery,Art Gallery,Thai Restaurant,Theater,Beer Store
3,North York,0,Furniture and Home Store,Clothing Store,Fashion Accessories Store,Party Supply Store,Boutique,Event Space,Vietnamese Restaurant,Coffee Shop,Flea Market,Education
4,Downtown Toronto,0,Coffee Shop,Sushi Restaurant,Fried Chicken Joint,Burger Joint,Café,Wings Joint,Seafood Restaurant,Sandwich Spot,Bubble Tea Shop,Restaurant
6,Scarborough,0,Fast Food Restaurant,Fuel Station,Falafel Restaurant,Eyecare Store,Exhibit,Event Space,Ethiopian Restaurant,Escape Room,Fashion Accessories Store,Electronics Store
...,...,...,...,...,...,...,...,...,...,...,...,...
97,Downtown Toronto,0,Coffee Shop,Café,Hotel,Restaurant,Deli,American Restaurant,Cocktail Bar,Thai Restaurant,Seafood Restaurant,Speakeasy
98,Etobicoke,0,River,Electronics Store,Doner Restaurant,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Empanada Restaurant,Concert Hall
99,Downtown Toronto,0,Coffee Shop,Sushi Restaurant,Japanese Restaurant,Gay Bar,Bubble Tea Shop,Burger Joint,Café,Italian Restaurant,Korean Restaurant,Theater
100,East Toronto,0,Fast Food Restaurant,Boutique,Pizzeria,Café,Smoke Shop,Sandwich Spot,Garden,Garden Center,Deli,Farmers Market
102,Etobicoke,0,Wings Joint,Supplement Store,Bakery,Beer Bar,Children's Clothing Store,Convenience Store,Discount Store,Fast Food Restaurant,Grocery Store,Sandwich Spot

Cluster 1

In [48]:

toronto_merged.loc[toronto_merged['Cluster_Labels'] == 1, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Borough,Cluster_Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,North York,1,Park,Food and Beverage Retail,Wings Joint,Electronics Store,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Empanada Restaurant
21,York,1,Park,Bakery,Fishing Store,Wings Joint,Empanada Restaurant,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Electronics Store
22,Scarborough,1,Korean BBQ Restaurant,Park,Coffee Shop,Escape Room,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Electronics Store,Empanada Restaurant
35,East York,1,Park,Convenience Store,Rental Car Location,Education,Doner Restaurant,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Electronics Store
52,North York,1,Park,Wings Joint,Empanada Restaurant,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Electronics Store,Escape Room
61,Central Toronto,1,Park,Organic Grocery,Bus Line,Wings Joint,Electronics Store,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education
63,York,1,Park,Convenience Store,Furniture and Home Store,Education,Doner Restaurant,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Electronics Store
66,North York,1,Park,Convenience Store,Jewelry Store,Empanada Restaurant,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Electronics Store,Escape Room
85,Scarborough,1,Park,Playground,Intersection,Wings Joint,Education,Doner Restaurant,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant
91,Downtown Toronto,1,Park,Hiking Trail,Playground,Wings Joint,Electronics Store,Doner Restaurant,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant
101,Etobicoke,1,Convenience Store,Park,Travel and Transportation,Falafel Restaurant,Eyecare Store,Exhibit,Event Space,Ethiopian Restaurant,Escape Room,Dog Park

Cluster 2

In [49]:
toronto_merged.loc[toronto_merged['Cluster_Labels'] == 2, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Borough,Cluster_Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
51,Scarborough,2,Motel,Harbor or Marina,Electronics Store,Doner Restaurant,Donut Shop,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Wings Joint

Cluster 3

In [50]:
toronto_merged.loc[toronto_merged['Cluster_Labels'] == 3, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Borough,Cluster_Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
50,North York,3,Clothing Store,Wings Joint,Escape Room,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Electronics Store,Empanada Restaurant,Ethiopian Restaurant
78,Scarborough,3,Clothing Store,Breakfast Spot,Escape Room,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Electronics Store,Empanada Restaurant,Wings Joint

Cluster 4

In [51]:
toronto_merged.loc[toronto_merged['Cluster_Labels'] == 4, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Borough,Cluster_Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
49,North York,4,Bakery,Wings Joint,Empanada Restaurant,Drugstore,Dumpling Restaurant,Eastern European Restaurant,Education,Electronics Store,Escape Room,Fast Food Restaurant